CREATE TABLE IF NOT EXISTS clients (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  coordinate_x DOUBLE PRECISION NOT NULL,
  coordinate_y DOUBLE PRECISION NOT NULL
);
